import React from 'react';
import Sidebar from '../components/SideBar';

const ReportGeneration = () => {
  const summary = {
    totalIncidents: 150,
    highSeverityIncidents: 30,
    commonProtocol: 'HTTP',
    topClassification: 'Suspicious Activity'
  };

  const incidents = [
    {
      timestamp: '2024-11-14 08:12:30',
      sourceIP: '192.168.1.10',
      destinationIP: '10.0.0.25',
      protocol: 'HTTP',
      classification: 'Suspicious Activity',
      severity: 'High'
    },
    {
      timestamp: '2024-11-14 08:15:45',
      sourceIP: '192.168.1.10',
      destinationIP: '10.0.0.50',
      protocol: 'FTP',
      classification: 'Potential Malware',
      severity: 'Medium'
    },
    {
      timestamp: '2024-11-14 08:18:12',
      sourceIP: '203.0.113.42',
      destinationIP: '192.168.1.20',
      protocol: 'ICMP',
      classification: 'Denial of Service',
      severity: 'Critical'
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <Sidebar />

      {/* Main Content */}
      <div className="ml-16 p-8">
        <div className="mx-auto max-w-screen-2xl">
          <h1 className="text-3xl font-bold text-center mb-6 text-navy-800">Report Generation</h1>

          <div className="rounded-lg bg-white p-6 shadow-md">
            <h2 className="mb-6 text-xl font-semibold text-navy-800">Report</h2>

            {/* Date Range */}
            <div className="mb-6">
              <span className="font-medium text-gray-700">Date Range: </span>
              <span className="text-gray-600">2024-11-01 To 2024-11-14</span>
            </div>

            {/* Summary Section */}
            <div className="mb-8">
              <h3 className="mb-4 text-lg font-medium text-navy-800">Summary</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• Total Incidents Detected: {summary.totalIncidents}</li>
                <li>• High Severity Incidents: {summary.highSeverityIncidents}</li>
                <li>• Most Common Protocol: {summary.commonProtocol}</li>
                <li>• Top Classification: {summary.topClassification}</li>
              </ul>
            </div>

            {/* Incident Log */}
            <div>
              <h3 className="mb-4 text-lg font-medium text-navy-800">Incident Log</h3>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-200 text-left">
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Timestamp</th>
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Source IP</th>
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Destination IP</th>
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Protocol</th>
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Classification</th>
                      <th className="bg-gray-50 px-4 py-2 text-sm font-medium text-gray-600">Severity</th>
                    </tr>
                  </thead>
                  <tbody>
                    {incidents.map((incident, index) => (
                      <tr key={index} className="border-b border-gray-100">
                        <td className="px-4 py-2 text-sm text-gray-600">{incident.timestamp}</td>
                        <td className="px-4 py-2 text-sm text-gray-600">{incident.sourceIP}</td>
                        <td className="px-4 py-2 text-sm text-gray-600">{incident.destinationIP}</td>
                        <td className="px-4 py-2 text-sm text-gray-600">{incident.protocol}</td>
                        <td className="px-4 py-2 text-sm text-gray-600">{incident.classification}</td>
                        <td className="px-4 py-2">
                          <span className={`rounded-full px-2 py-1 text-xs font-medium
                            ${incident.severity === 'Critical' ? 'bg-red-100 text-red-800' : 
                              incident.severity === 'High' ? 'bg-orange-100 text-orange-800' : 
                              'bg-yellow-100 text-yellow-800'}`}>
                            {incident.severity}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Report Footer */}
            <div className="mt-8 flex items-center justify-between border-t border-gray-200 pt-4">
              <div className="text-sm text-gray-600">
                <div>Report Generated On: 2024-11-14</div>
                <div>Generated By: AI-Driven APT Detection System</div>
              </div>
              <button className="rounded bg-navy-800 px-4 py-2 text-sm font-medium text-white border- hover:bg-navy-700">
                DOWNLOAD PDF
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportGeneration;